// server/services/leadService.js
// MongoDB data layer — Replaces the old Airtable abstraction

const Lead = require('../models/Lead');

// ── CREATE ───────────────────────────────────────────────────────────────────

async function createLead(leadData) {
  const lead = new Lead({
    name: leadData.name,
    email: leadData.email,
    phone: leadData.phone,
    university: leadData.university,
    course: leadData.course,
    source: leadData.source || 'Website',
    status: leadData.status || 'New',
    assignedCounselor: leadData.assignedCounselor || '',
    contactedBy: leadData.contactedBy || '',
    notes: leadData.notes || '',
    // createdAt is auto-generated by Mongoose timestamps
  });
  
  const savedLead = await lead.save();
  return formatLeadRecord(savedLead);
}

// ── FIND RECENT BY PHONE (24h duplicate check) ──────────────────────────────

async function findRecentLeadByPhone(phone) {
  const cutoff = new Date(Date.now() - 24 * 60 * 60 * 1000);
  const records = await Lead.find({
    phone,
    createdAt: { $gte: cutoff }
  }).limit(1);
  return records.map(formatLeadRecord);
}

// ── GET ALL LEADS (paginated + filtered) ─────────────────────────────────────

async function getAllLeads(options = {}) {
  const { university, course, status, search, page = 1, limit = 20 } = options;
  const query = {};

  if (university) query.university = university;
  if (course) query.course = course;
  if (status) query.status = status;
  if (search) {
    const s = search.toLowerCase();
    query.$or = [
      { name: { $regex: s, $options: 'i' } },
      { email: { $regex: s, $options: 'i' } },
      { phone: { $regex: s, $options: 'i' } }
    ];
  }

  const pageInt = parseInt(page, 10);
  const limitInt = parseInt(limit, 10);
  const skip = (pageInt - 1) * limitInt;

  const [records, totalCount] = await Promise.all([
    Lead.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limitInt),
    Lead.countDocuments(query)
  ]);

  return {
    leads: records.map(formatLeadRecord),
    totalCount,
    page: pageInt,
    limit: limitInt,
    totalPages: Math.ceil(totalCount / limitInt) || 1,
  };
}

// ── EXPORT ALL (for CSV) ─────────────────────────────────────────────────────

async function getAllLeadsForExport(filters = {}) {
  const { university, course, status } = filters;
  const query = {};

  if (university) query.university = university;
  if (course) query.course = course;
  if (status) query.status = status;

  const records = await Lead.find(query).sort({ createdAt: -1 });
  return records.map(formatLeadRecord);
}

// ── UPDATE LEAD ──────────────────────────────────────────────────────────────

async function updateLead(id, updates) {
  const allowedFields = ['status', 'notes', 'assignedCounselor', 'contactedBy'];
  const updateDoc = {};

  allowedFields.forEach((field) => {
    if (updates[field] !== undefined) {
      updateDoc[field] = updates[field];
    }
  });

  const updatedLead = await Lead.findByIdAndUpdate(
    id,
    { $set: updateDoc },
    { new: true, runValidators: true }
  );

  if (!updatedLead) throw new Error('Lead not found');
  return formatLeadRecord(updatedLead);
}

// ── FILTER OPTIONS ───────────────────────────────────────────────────────────

async function getFilterOptions() {
  const [universities, courses, statuses] = await Promise.all([
    Lead.distinct('university'),
    Lead.distinct('course'),
    Lead.distinct('status')
  ]);

  return {
    universities: universities.filter(Boolean),
    courses: courses.filter(Boolean),
    statuses: statuses.filter(Boolean),
  };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function formatLeadRecord(record) {
  return {
    id: record._id.toString(),
    name: record.name,
    email: record.email,
    phone: record.phone,
    university: record.university,
    course: record.course,
    source: record.source,
    status: record.status,
    assignedCounselor: record.assignedCounselor,
    contactedBy: record.contactedBy,
    notes: record.notes,
    createdAt: record.createdAt,
    updatedAt: record.updatedAt
  };
}

module.exports = {
  createLead,
  findRecentLeadByPhone,
  getAllLeads,
  getAllLeadsForExport,
  updateLead,
  getFilterOptions,
};
